---
title: "Midterm"
author: "Suyeon Ryu"
date: '2020 10 5'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, eval=TRUE, echo=FALSE}
library(tidyverse)
library(ggplot2)
library(data.table)
library(dplyr)

midt<- data.table::fread("C:/Users/suyeo/PM566/midterm/data/BYAREA.txt")



cln <- midt[midt$SITE == "Colon and Rectum"]

cln_mort <- cln[cln$EVENT_TYPE == "Mortality"]
cln_inc <- cln[cln$EVENT_TYPE == "Incidence"]

# Noticed some rates are still characters. In order to plot, need to change to numeric!

cln_mort <- cln_mort %>% mutate(
  CRUDE_RATE = as.numeric(CRUDE_RATE),
  YEAR = as.numeric(YEAR),
  AGE_ADJUSTED_RATE = as.numeric(AGE_ADJUSTED_RATE),
)


cln_inc <- cln_inc %>% mutate(
  CRUDE_RATE = as.numeric(CRUDE_RATE),
  YEAR = as.numeric(YEAR),
  AGE_ADJUSTED_RATE = as.numeric(AGE_ADJUSTED_RATE),
)


# checking and removing missing values 
cln_mort %>%
  select(everything()) %>%
  summarise_all(funs(sum(is.na(.))))

cln_inc %>%
  select(everything()) %>%
  summarise_all(funs(sum(is.na(.))))

cln_mort <- na.omit(cln_mort)
cln_inc <- na.omit(cln_inc)




```

# trimming down (subsetting) the data because it is too big

```{r, eval=TRUE}


# trimming down (subsetting) the data because it is too big

cln_inc <- cln_inc %>% group_by(CRUDE_RATE) %>%
  slice(seq(1, n(), by = 20))
cln_mort <-  cln_mort %>% group_by(CRUDE_RATE) %>%
  slice(seq(1, n(), by = 20))

# Trend of colon cancer incidence and mortality over the years (maybe line graph)

ggplot(cln_mort, aes(x=YEAR, y=CRUDE_RATE))+
  geom_point(color="red")+
  theme_minimal()+
  geom_smooth(method="loess", color="red", fill="darkred")+
  ggtitle("U.S. Colon Cancer Mortality Crude Rate")


ggplot(cln_inc, aes(x=YEAR, y=CRUDE_RATE))+
  geom_point(color="blue")+
  theme_minimal()+
  geom_smooth(method="loess")+
  ggtitle("U.S. Colon Cancer Incidence Crude Rate")



```


# EAST versus WEST
```{r}
#EAST versus WEST

#EAST will include New York, Pennsylvania, New Jersey, Virginia, North and South Carolina, Georgia
#WEST will include Washington, Oregon, California

us_map <- map_data("state")

east_states <- c("new york", "pennsylvania","new jersey","virginia","north carolina","south carolina","georgia")
west_states <- c("washington","oregon","california")

ggplot(us_map, aes(x=long, y=lat, group = group)) +
  geom_polygon(fill="grey", colour = "white") +
  geom_polygon(fill="palevioletred1", data = filter(us_map, region %in% east_states)) +
  geom_polygon(fill="mediumpurple", data = filter(us_map, region %in% west_states))+
  ggtitle("U.S Colon Cancer Comparison Covered Area East versus West")


#make new variables for east and west states

cln_inc$westeast <- ifelse(cln_inc$AREA == "New York"|cln_inc$AREA == "Pennsylvania"|cln_inc$AREA == "New Jersey"|cln_inc$AREA == "Virginia"|cln_inc$AREA == "North Carolina"|cln_inc$AREA == "South Carolina"|cln_inc$AREA == "Georgia", "East Coast",
                           ifelse(cln_inc$AREA =="Washington"|cln_inc$AREA =="Oregon"|cln_inc$AREA == "California", "West Coast","Not Considered" ))





#plotting bargraph of crude rate including "non considering area"
p <- ggplot(data=cln_inc, aes(x=YEAR, y=CRUDE_RATE, fill=westeast))+
  geom_bar(stat="identity", color="black", position=position_dodge())+
  scale_fill_manual(values=c("palevioletred1","#999999","mediumpurple"))+
  theme_minimal()+
  ggtitle("U.S. Colon Cancer Incidence Crude Rate by Areas")

p

#excluding not considered area from the data set

cln3 <-cln_inc[!(cln_inc$westeast=="Not Considered"),]

#plotting scatterplot of crude rate east versus west

ggplot(data=cln3, aes(x=YEAR, y=CRUDE_RATE, color=westeast, shape=westeast)) +
  geom_point() + 
  geom_smooth(method=lm, se=TRUE, fullrange=TRUE)+
  scale_shape_manual(values=c(3, 17))+ 
  scale_color_manual(values=c("palevioletred1","mediumpurple"))+
  scale_size_manual(values=c(7,7))+
  theme(legend.position="right")+
  ggtitle("U.S. Colon Cancer Incidence Crude Rate West Coast vs. East Coast")




```



# age adjusted 
```{r}

#removing outlier
cln4 <- subset(cln3, cln3$AGE_ADJUSTED_RATE < 130)

#plot 
ggplot(data=cln4, aes(x=YEAR, y=AGE_ADJUSTED_RATE, fill=westeast))+
  geom_bar(stat="identity", color="black", position=position_dodge())+
  scale_fill_manual(values=c("palevioletred1","mediumpurple"))+
  theme_minimal()

ggplot(data=cln4, aes(x=YEAR, y=AGE_ADJUSTED_RATE, color=westeast, shape=westeast)) +
  geom_point() + 
  geom_smooth(method=lm, se=TRUE, fullrange=TRUE)+
  scale_shape_manual(values=c(3, 17))+ 
  scale_color_manual(values=c("palevioletred1","mediumpurple"))+
  scale_size_manual(values=c(7,7))+
  theme(legend.position="right")+
  ggtitle("U.S. Colon Cancer AGE Adjusted Rate West Coast vs. East Coast")



```





```{r}
# Do the same with mortality 



cln_mort$westeast <- ifelse(cln_mort$AREA == "New York"|cln_mort$AREA == "Pennsylvania"|cln_mort$AREA == "New Jersey"|cln_mort$AREA == "Virginia"|cln_mort$AREA == "North Carolina"|cln_mort$AREA == "South Carolina"|cln_mort$AREA == "Georgia", "East Coast",
                           ifelse(cln_mort$AREA =="Washington"|cln_mort$AREA =="Oregon"|cln_mort$AREA == "California", "West Coast","Not Considered" ))





#plotting bargraph of crude rate including "non considering area"
mort2 <- ggplot(data=cln_mort, aes(x=YEAR, y=CRUDE_RATE, fill=westeast))+
  geom_bar(stat="identity", color="black", position=position_dodge())+
  scale_fill_manual(values=c("palevioletred1","#999999","mediumpurple"))+
  theme_minimal()

mort2

#excluding not considered area from the data set

mort3 <-cln_mort[!(cln_mort$westeast=="Not Considered"),]

#plotting scatterplot of crude rate east versus west


ggplot(data=mort3, aes(x=YEAR, y=CRUDE_RATE, color=westeast, shape=westeast)) +
  geom_point() + 
  geom_smooth(method=lm, se=TRUE, fullrange=TRUE)+
  scale_shape_manual(values=c(3, 17))+ 
  scale_color_manual(values=c("palevioletred1","mediumpurple"))+
  scale_size_manual(values=c(7,7))+
  theme(legend.position="right")+
  ggtitle("U.S. Colon Cancer Mortality Crude Rate West Coast vs. East Coast")



ggplot(data=mort3, aes(x=YEAR, y=AGE_ADJUSTED_RATE, color=westeast, shape=westeast)) +
  geom_point() + 
  geom_smooth(method=lm, se=TRUE, fullrange=TRUE)+
  scale_shape_manual(values=c(3, 17))+ 
  scale_color_manual(values=c("palevioletred1","mediumpurple"))+
  scale_size_manual(values=c(7,7))+
  theme(legend.position="right")+
  ggtitle("U.S. Colon Cancer AGE Adjusted Mortality Rate West Coast vs. East Coast")



```


